inherit_from: .rubocop_todo.yml

# Due to old Ruby 1.8.x
Layout/DotPosition:
  EnforcedStyle: trailing

# Due to old Ruby 1.9.x
Style/Dir:
  Enabled: false

# Dut to old Ruby 1.8.x
Style/EachWithObject:
  Enabled: false

# Dut to old Ruby 1.8.x
Style/EmptyBlockParameter:
  Enabled: false

# Due to old Ruby 1.8.x
Style/Lambda:
  EnforcedStyle: lambda

# Due to old Ruby 2.2.x
Style/SafeNavigation:
  Enabled: false

# Due to old Ruby 1.8.x
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

# Due to old Ruby
Layout/IndentHeredoc:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Naming/VariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/AsciiComments:
  Enabled: false

# Due to old Ruby 1.9.x
Style/BracesAroundHashParameters:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/Documentation:
  Enabled: false

# Due to old Ruby
Style/Encoding:
  Enabled: false

# Due to old Ruby
Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/NegatedWhile:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 6

Style/WordArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiterals:
  Enabled: false

# Due to old Ruby 1.8.x
Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/YodaCondition:
  EnforcedStyle: forbid_for_equality_operators_only
