# -*- coding: utf-8 -*-

require "rake/testtask"

task :default => :test

desc 'Clean coverage resuts'
task :clean_coverage do
  if RUBY_VERSION > '1.8.x'
    require 'simplecov'
    resultset_path = SimpleCov::ResultMerger.resultset_path
    FileUtils.rm resultset_path if File.exist? resultset_path
  end
end

namespace :test do
  Rake::TestTask.new(:dicebots) do |t|
    t.description = 'ダイスボット'

    t.test_files = [
      'test/setup',
      'test/testDiceBots.rb',
    ]
    t.libs = [
      'test',
      '.',
      'irc'
    ]

    unless RUBY_VERSION < '1.9'
      t.ruby_opts = [
        '--enable-frozen-string-literal'
      ]
    end
  end

  Rake::TestTask.new(:unit) do |t|
    t.description = 'ユニットテスト'
    t.test_files = [
      'test/setup',
      'test/testDiceBotLoaders.rb',
      'test/testDiceBotPrefixesCompatibility.rb'
    ]
  end
end

task :test => [
  :clean_coverage,
  'test:dicebots',
  'test:unit',
]

if RUBY_VERSION >= '2.3'
  require 'rubocop/rake_task'
  RuboCop::RakeTask.new
  task :test => [:rubocop]
end
